{
 "title": "{{component}}",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "memory used percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "node_memory_used_percent{name=\"{{env}}-{{component}}\"}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(name)(floor(rate(node_cpu_seconds_total{mode=\"idle\" , name=\"{{env}}-{{component}}\"}[1m])*100)))"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(name)(floor(rate(node_cpu_seconds_total{mode=\"idle\" , name=\"{{env}}-{{component}}\"}[1m])*100)))"
    }
   ]
  },
  {
   "title": "component-process",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"{{env}}-{{component}}\",exported_name=\"{{service_name}}.service\",state=\"active\"}"
    }
   ]
  }
 ]
}