
- name: Install nginx
  ansible.builtin.yum:
    name: httpd
    state: installed
    
- name: remove old http docs
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
    
- name: Create a http document directory 
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory